name: Build RustDesk Windows x86_64

on:
  push:
    branches:
      - master
      - main
      - windows
  pull_request:
    branches:
      - master
      - main
      - windows
  workflow_dispatch:

env:
  RUST_VERSION: "1.75"
  FLUTTER_VERSION: "3.24.5"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  VERSION: "1.4.8"

jobs:
  build-windows-x64:
    name: Build Windows x86_64
    runs-on: windows-2022
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: x86_64-pc-windows-msvc
          components: rustfmt

      - name: Setup MSVC developer environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false

      - name: Install vcpkg dependencies
        shell: bash
        env:
          VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static
        run: |
          if ! $VCPKG_ROOT/vcpkg \
            install \
            --triplet x64-windows-static \
            --x-install-root="$VCPKG_ROOT/installed"; then
            find "${VCPKG_ROOT}/" -name "*.log" | while read -r _1; do
              echo "$_1:"
              echo "======"
              cat "$_1"
              echo "======"
              echo ""
            done
            exit 1
          fi

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build RustDesk
        shell: bash
        env:
          VCPKG_ROOT: C:\vcpkg
          INCLUDE: C:\vcpkg\installed\x64-windows-static\include
          LIB: C:\vcpkg\installed\x64-windows-static\lib
        run: |
          export PATH="/c/vcpkg/installed/x64-windows-static/bin:$PATH"
          python ./build.py --portable --flutter --skip-portable-pack --hwcodec --vram
          mv ./flutter/build/windows/x64/runner/Release ./rustdesk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-x64
          path: rustdesk
          retention-days: 30
